name: clock
version: 0.1.0
author: Sean Eagan <seaneagan1@gmail.com>
description: Provides testable replacements for the system clock APIs (`new DateTime.now()` and `new Stopwatch()`).
homepage: https://github.com/seaneagan/clock
dev_dependencies:
  mock: any
  unittest: any
